apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bb-backend-rolebinding
  namespace: bb
subjects:
- kind: ServiceAccount
  name: bb-backend-service
  namespace: bb
roleRef:
  kind: Role
  name: bb-backend-role
  apiGroup: rbac.authorization.k8s.io

