apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: playground-storage
  namespace: bb
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: do-block-storage
