apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-bb
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /mnt/nfs-share/bb
    server: 10.104.0.3
